### ISSUE TITLE
UX-fMRIPrep: Input files

### ISSUE THREAD

**Issue by Najmahan** [aces/cbrain-plugins-neuro#165]
Problem: To run the command, the user must supplement the fslicense file. If they don't, it automatically fills the field with the name of the only file selected. 

Solution: Improve the error message and tell the user what they need to do to circumvent this problem.

Confusion: Wha if I choose two BIDS folders, but no license file?

**Comment by prioux** [comment]
This is a general problem with the Boutiques integrator, not specific to FMRIPrep.

The form never autoselects the files for the input fields, by the way. See screenshot below, where I selected just one file.

I've re-opened the issue here: https://github.com/aces/cbrain/issues/1051

![Screen Shot 2020-11-09 at 15 56 11](https://user-images.githubusercontent.com/777588/98595577-296e2f80-22a4-11eb-9561-1e155ca4618f.png)

**Comment by prioux** [comment]
Addendum: if you choose two BIDS folders, the task will crash. There is support for specifying a mandatory file type for inputs, but the descriptor for FMRIPrep doesn't specify a type.
